export const  FETCH_STATES_REQUEST = 'FETCH_STATES_REQUEST';
export const  FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const  FETCH_STATES_FAILURE = 'FETCH_STATES_FAILURE';

export const  FETCH_REVSNRE_REQUEST = 'FETCH_REVSNRE_REQUEST';
export const  FETCH_REVSNRE_SUCCESS = 'FETCH_REVSNRE_SUCCESS';
export const  FETCH_REVSNRE_FAILURE = 'FETCH_REVSNRE_FAILURE';

export const  FETCH_BREAKDOWN_REQUEST = 'FETCH_BREAKDOWN_REQUEST';
export const  FETCH_BREAKDOWN_SUCCESS = 'FETCH_BREAKDOWN_SUCCESS';
export const  FETCH_BREAKDOWN_FAILURE = 'FETCH_BREAKDOWN_FAILURE';

export const  FETCH_TOP_PLANTS_REQUEST = 'FETCH_TOP_PLANTS_REQUEST';
export const  FETCH_TOP_PLANTS_SUCCESS = 'FETCH_TOP_PLANTS_SUCCESS';
export const  FETCH_TOP_PLANTS_FAILURE = 'FETCH_TOP_PLANTS_FAILURE';